name: Build and Deploy calorieCounter Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Inject Azure SQL Connection String into appsettings.json
        run: |
          $fileContent = Get-Content -Path "./appsettings.json"
          $fileContent = $fileContent -replace '"AzureSQL": "KEY"', '"AzureSQL": "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"'
          Set-Content -Path "./appsettings.json" -Value $fileContent   
          
      - name: Inject Google Client ID into appsettings.json
        run: |
          $fileContent = Get-Content -Path "./appsettings.json"
          $fileContent = $fileContent -replace '"GoogleClientId": "ID"', '"GoogleClientId": "${{ secrets.GOOGLE_CLIENT_ID }}"'
          Set-Content -Path "./appsettings.json" -Value $fileContent

      - name: Inject Google Client Secret into appsettings.json
        run: |
          $fileContent = Get-Content -Path "./appsettings.json"
          $fileContent = $fileContent -replace '"GoogleClientSecret": "SECRET"', '"GoogleClientSecret": "${{ secrets.GOOGLE_CLIENT_SECRET }}"'
          Set-Content -Path "./appsettings.json" -Value $fileContent

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/calorieCounter_backend"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/calorieCounter_backend"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4CE8B46E3CDA477F98A52AADF7569D66 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E67199BD489D4AE183F9B44DFEF0B257 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EDABE5A0782E47D287D4C58250C29D73 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calorieCounter-backend'
          slot-name: 'Production'
          package: .
          